FROM python:3.14-rc-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    fluidsynth \
    freepats \
    lilypond \
    build-essential \
    libasound2-dev \
    libffi-dev \
    zlib1g-dev \
    libjpeg-dev \
    git \
    vim \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /app

RUN uv init .
RUN uv add python-dotenv \
           pydantic \
           loguru \
           tqdm \
           scipy \
           music21 \
           pyfluidsynth \
           langchain_ollama \
           pytest

CMD ["/bin/bash"]